#### Deep Learning Softmax

In [ ]:
"""Softmax."""

scores = [3.0, 1.0, 0.2]

import numpy as np

def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    soft = np.divide(np.exp(x),np.sum(np.exp(x),axis=0))
    return soft


print(softmax(scores))

# Plot softmax curves
import matplotlib.pyplot as plt
x = np.arange(-2.0, 6.0, 0.1)
scores = np.vstack([x, np.ones_like(x), 0.2 * np.ones_like(x)])

plt.plot(x, softmax(scores).T, linewidth=2)
plt.show()

[ 0.8360188   0.11314284  0.05083836]


In [57]:
def softmax(x):
    soft = np.divide(np.exp(x),np.sum(np.exp(x),axis=0))
    return soft

In [59]:
a = [[1, 2], [2, 3], [3, 4]]

scores = [3.0, 1.0, 0.2]

x = np.array([[1, 2, 3, 6],
                   [2, 4, 5, 6],
                   [3, 8, 7, 6]])

print softmax(a)

print softmax(scores)

print softmax(x)

[[ 0.09003057  0.09003057]
 [ 0.24472847  0.24472847]
 [ 0.66524096  0.66524096]]
[ 0.8360188   0.11314284  0.05083836]
[[ 0.09003057  0.00242826  0.01587624  0.33333333]
 [ 0.24472847  0.01794253  0.11731043  0.33333333]
 [ 0.66524096  0.97962921  0.86681333  0.33333333]]


In [55]:
def softmax(x):
    soft = np.divide(np.exp(x),np.sum(np.exp(x),axis=0))
    return soft



In [56]:
print softmax(a)

print softmax2(a)

[[ 0.09003057  0.09003057]
 [ 0.24472847  0.24472847]
 [ 0.66524096  0.66524096]]
[[0 0]
 [0 0]
 [0 0]]


In [60]:
# numpy

a = np.arange(15).reshape(3, 5)

In [61]:
a.shape

(3, 5)

In [62]:
a.ndim

2

In [63]:
a.dtype.name

'int64'

In [65]:
a.size

15

In [66]:
type(a)

numpy.ndarray

In [70]:
b = np.array([6, 7, 8])
print b
print type(b)
b.dtype

[6 7 8]
<type 'numpy.ndarray'>


dtype('int64')

In [71]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [72]:
b = np.array([[1.5,2,3], [4,5,6])

SyntaxError: invalid syntax (<ipython-input-72-cde43b7e0fe9>, line 1)

In [74]:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [78]:
print b.shape

b[:,1]

(5, 4)


array([ 1, 11, 21, 31, 41])

In [81]:
b[-1,-1]

43

In [83]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
                [[100,101,102],
                [110,112,113]]])

c.shape

(2, 2, 3)

In [86]:
# same as c[1,:,:] or c[1]
c[1,...]                                   

array([[100, 101, 102],
       [110, 112, 113]])

In [87]:
# same as c[:,:,2]
c[...,2]                                   

array([[  2,  13],
       [102, 113]])

In [8]:
# quiz numerical stability
a=1000000000.0 
for i in range(1000000):
    a += 0.000001
a -= 1000000000.0
print a

0.953674316406


In [6]:
x

1.0

In [ ]:
a=5

In [ ]:
print a